# Task A3

#### Import Libraries

In [2]:
from motionchart.motionchart import MotionChart
import pandas as pd
import numpy as np

#### Making the dataframe using concat

In [44]:
df1=pd.read_excel('energy_data.xlsx','VIC')
df2=df=pd.read_excel('energy_data.xlsx','TAS')
df3=df=pd.read_excel('energy_data.xlsx','QLD')
df4=df=pd.read_excel('energy_data.xlsx','SA')
df5=df=pd.read_excel('energy_data.xlsx','WA')
df6=df=pd.read_excel('energy_data.xlsx','NT')
df7=df=pd.read_excel('energy_data.xlsx','NSW')
df=pd.concat([df1,df2,df3,df4,df5,df6,df7],ignore_index=True)
df.replace(np.NaN,0,inplace=True)
df

,State,Fuel_Type,Category,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,VIC,Black coal,Non-renewable fuels,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31.9,36.3,0.0
1,VIC,Brown coal,Non-renewable fuels,52094.0,51541.7,51066.5,52059.7,45317.6,43977.7,48336.8,46202.2,43557.8,36067.0
2,VIC,Natural gas,Non-renewable fuels,1451.9,1697.9,1289.8,1142.5,3247.7,3239.3,2390.9,1892.2,2658.7,3899.4
3,VIC,Oil products,Non-renewable fuels,20.4,1.1,38.2,4.0,10.7,145.8,156.0,70.6,109.3,164.8
4,VIC,Other,Non-renewable fuels,61.1,115.9,114.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,NSW,Wind,Renewable fuels,41.3,432.5,530.1,697.6,832.6,899.2,1376.0,1898.8,1872.0,2448.7
73,NSW,Hydro,Renewable fuels,3173.7,3820.8,5267.0,3792.8,5651.6,4213.1,3113.7,5191.0,6139.1,4844.6
74,NSW,Large-scale solar PV,Renewable fuels,0.0,0.0,0.0,0.0,0.0,10.6,60.2,399.5,567.6,700.0
75,NSW,Small-scale solar PV,Renewable fuels,36.3,119.2,526.3,657.7,857.6,964.9,1211.2,1461.9,1706.8,2095.8
76,NSW,Geothermal,Renewable fuels,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Now let's look at the relationship between all variables impacting the energy generation over time. Ensure that you have combined all the data from the different states. Ensure that your data is aggregated by year, state, the total energy produced (total_production), and has a separate column for each of the fuel types.

#### Modifying the dataframe to produce the motionchart

In [153]:
years=[i for i in range(2009,2019)]
df2=pd.melt(df,id_vars=['State','Fuel_Type','Category'],var_name='Year',value_name='Fuel_Generated',value_vars=years)
data=[]
state=['VIC','TAS','QLD','SA','WA','NT','NSW']
year=np.arange(2009,2019,1)
total_production=[]
for i in year:
    for j in state:
        total_production.append(df[df['State']==j][i].sum())
total_production=np.array(total_production, dtype='float64')
for year in range(2009,2019):
    data_tmp=pd.DataFrame({'State':['VIC','TAS','QLD','SA','WA','NT','NSW'],
                 'Year':[year for i in range(7)],
                  'Black_Coal': np.array(df2[(df2.Fuel_Type=='Black coal') & (df2.Year==year)]['Fuel_Generated']),
                  'Brown_Coal':np.array(df2[(df2.Fuel_Type=='Brown coal') & (df2.Year==year)]['Fuel_Generated']),
                  'Natural_Gas':np.array(df2[(df2.Fuel_Type=='Natural gas') & (df2.Year==year)]['Fuel_Generated']),
                   'Oil_Products':np.array(df2[(df2.Fuel_Type=='Oil products') & (df2.Year==year)]['Fuel_Generated']),
                   'Other':np.array(df2[(df2.Fuel_Type=='Other') & (df2.Year==year)]['Fuel_Generated']),
                  'Biomass':np.array(df2[(df2.Fuel_Type=='Biomass') & (df2.Year==year)]['Fuel_Generated']),
                  'Wind':np.array(df2[(df2.Fuel_Type=='Wind') & (df2.Year==year)]['Fuel_Generated']),
                  'Hydro':np.array(df2[(df2.Fuel_Type=='Hydro') & (df2.Year==year)]['Fuel_Generated']),
                  'Large-Scale_Solar_PV':np.array(df2[(df2.Fuel_Type=='Large-scale solar PV') & (df2.Year==year)]['Fuel_Generated']),
                  'Small-Scale_Solar_PV':np.array(df2[(df2.Fuel_Type=='Small-scale solar PV') & (df2.Year==year)]['Fuel_Generated']),
                  'Geothermal':np.array(df2[(df2.Fuel_Type=='Geothermal') & (df2.Year==year)]['Fuel_Generated'])
                  })
    data.append(data_tmp)
data=pd.concat(data,ignore_index=True)
data['total_production']=total_production
data

,State,Year,Black_Coal,Brown_Coal,Natural_Gas,Oil_Products,Other,Biomass,Wind,Hydro,Large-Scale_Solar_PV,Small-Scale_Solar_PV,Geothermal,total_production
0,VIC,2009,0.0,52094.0,1451.9,20.4,61.1,292.0,573.0,557.8,0.0,24.1,0.0,55074.3
1,TAS,2009,0.0,0.0,705.3,64.5,0.0,25.1,486.9,7313.6,0.0,1.8,0.0,8597.2
2,QLD,2009,50882.2,0.0,9257.2,711.4,691.8,1588.5,27.3,820.2,0.0,50.8,0.5,64029.9
3,SA,2009,0.0,4887.4,7371.4,63.2,337.4,86.1,2020.2,4.1,0.0,23.4,0.0,14793.2
4,WA,2009,8738.0,0.0,14556.1,1464.4,2153.0,119.6,675.1,0.0,0.0,18.7,0.0,27724.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,QLD,2018,53480.2,0.0,11112.1,1001.9,0.0,1434.1,28.5,657.3,171.5,2760.9,0.0,70646.5
66,SA,2018,0.0,0.0,7703.5,137.5,0.0,89.1,5572.9,6.4,20.0,1163.4,0.0,14692.8
67,WA,2018,10960.9,0.0,24687.9,2540.9,0.0,153.0,1593.0,217.9,45.6,1196.4,0.0,41395.6
68,NT,2018,0.0,0.0,2420.2,969.0,0.0,7.1,0.0,0.0,30.5,85.8,0.0,3512.6
69,NSW,2018,57151.5,0.0,3039.5,415.5,0.0,1164.4,2448.7,4844.6,700.0,2095.8,0.0,71860.0

### 1. Use Python to build a Motion Chart, that 
### â€‹ Visualises the energy production trend for Australia overtime.
### â€‹  The motion chart should show the units of energy production using Wind on the x-axis,
### â€‹  The energy production using  Natural gas on the y-axis, 
### â€‹  The colour represents the states/territories
### â€‹ The bubble size should show the total_production

#### The following html code block is just to make sure that you will see the entire motion chart nicely in the output cell

In [147]:
%%html
<style>
.output_wrapper, .output {
    height:auto !important;
    max-height:1000px;  /* your desired max-height here */
}
.output_scroll {
    box-shadow:none !important;
    webkit-box-shadow:none !important;
}
</style>

#### Generating the motionchart to show it in the notebook

In [154]:
mChart = MotionChart(df = data,key='Year', x='Wind', y='Natural_Gas', xscale='linear', yscale='linear',
                     size='total_production', color='State')
mChart.to_notebook()

### 2.b) Which state relied most on natural gas for energy production in 2013? Please supportyour answer with any relevant python code and the motion chart screenshot.

In [155]:
highest=0 #Natural Gas is in the fifth column or position 4 as per python
row_highest=0
for row in range(70):
    if data.iloc[row,4]>highest:
        highest=df.iloc[row,4]
        row_highest=row
print('The state that relied the most on Natural Gas Production was:',df.iloc[row_highest,0])

The state that relied the most on Natural Gas Production was: VIC